name: shell Commands
on: [push]
jobs:
 run-shell-command:
  runs-on: ubuntu-latest
  

  steps:
   - name: Checkout
     uses: actions/checkout@v2
     with:
      fetch-depth: 0
   - name: echo a string
     run: echo "Hello World"
   - name: multiline script
     run: |
      node -v
      npm -v
      python -v
   - name: tttt
     run: |
          pwd
          ls -ltr
   - name: Run Tagging code
     run: |
       python ./data-service/tag.py       
   - name: get environment variable
     run:  |
        echo ${{ env.my_date }}
        echo ${{ env.my_var }}
        echo my var is ${{ env.my_var }}
   - name: Push version file into main
     run: |
       git config --global user.email "a@b.com"
       git config --global user.name "runner"
       git branch
       cat data-service/version.txt
       git status
       git commit -m "tttttttttttttttttttttttt"
       git add .
       git push 

