name: shell Commands
on: [push]
jobs:
 run-shell-command:
  runs-on: ubuntu-latest
  steps:
   - name: echo a string
     run: echo "Hello World"
   - name: multiline script
     run: |
      node -v
      npm -v
    
   - name: python Command
     shell: python
     run: |
       import os
       from datetime import datetime as dt
       env_file = os.getenv('GITHUB_ENV')
       x=dt.now()
       with open(env_file, "a") as myfile:
          myfile.write("my_date=x")
   - name: get environment variable
     run:  echo ${{ env.my_date }}

