name: shell Commands
on: [push]
jobs:
 run-shell-command:
  runs-on: ubuntu-latest
  

  steps:
   - name: Checkout
     uses: actions/checkout@v2
     with:
      fetch-depth: 0
   - name: echo a string
     run: echo "Hello World"
   - name: multiline script
     run: |
      node -v
      npm -v
   - name: tttt
     run: |
          pwd
      
    
   - name: python Command
     shell: python
     run: |
       import os
       from datetime import datetime as dt
       env_file = os.getenv('GITHUB_ENV')
       path  = os.getcwd()
       print(path)

       version_path  = f'{os.path.dirname(path)}/github_actions_test/.github/workflows/version.txt'
       print(version_path)
       x=dt.now()
       with open(version_path, "r") as f:
          line  = f.readline()

       with open(env_file, "a") as myfile:
          myfile.write(f"my_date={x}\n")
          myfile.write(f"my_var={line}")
       
       
   - name: get environment variable
     run:  |
        echo ${{ env.my_date }}
        echo ${{ env.my_var }}
        echo my var is ${{ env.my_var }}

